const actionTypes = {
  WEBCAM_STREAM_REQUEST: 'WEBCAM_STREAM_REQUEST',
  WEBCAM_STREAM_REQUEST_ERROR: 'WEBCAM_STREAM_REQUEST_ERROR',
  WEBCAM_STREAM_REQUEST_SUCCESS: 'WEBCAM_STREAM_REQUEST_SUCCESS',
  WEBCAM_SOURCES_REQUEST: 'WEBCAM_SOURCES_REQUEST',
  WEBCAM_SOURCES_REQUEST_ERROR: 'WEBCAM_SOURCES_REQUEST_ERROR',
  WEBCAM_SOURCES_REQUEST_SUCCESS: 'WEBCAM_SOURCES_REQUEST_SUCCESS',
  WEBCAM_SOURCES_NEXT: 'WEBCAM_SOURCES_NEXT'
};

const dimensions = {
  WIDTH: 200,
  HEIGHT: 100
};

export { actionTypes, dimensions };
